### ISSUE TITLE
0.1.0 release doesn't contain /dist directory

### ISSUE THREAD

**Issue by elseloop** [ole-treichel/storybook-react-to-static-markup#2]
0.1.0 breaks builds since importing it isn't possible. Assuming something went wrong when you last ran `build` for release.

The complete contents of `/storybook-react-to-static-markup` when installed via npm/yarn:

<img width="217" alt="Screen Shot 2019-08-13 at 4 01 50 PM" src="https://user-images.githubusercontent.com/1466832/62983297-b4335680-bde3-11e9-83c9-445caaef3e50.png">

**Comment by ole-treichel** [comment]
Whoops, sorry something went wrong. Version 0.1.1 contains the dist directory. Sorry for the inconvenience 😅
