### ISSUE TITLE
Display CSS as well?

### ISSUE THREAD

**Issue by steve-vuori** [ole-treichel/storybook-react-to-static-markup#6]
Is there anyway to get this addon to display CSS as well? Its a request from my designer I would love to include in our Storybook instance. Thank you!

**Comment by ole-treichel** [comment]
Hi, could you describe this a bit more? If I understand correctly you would want a second panel that shows the css of all classnames in use by the component, is this correct?

**Comment by steve-vuori** [comment]
@ole-treichel 
Thank you so much for you assistance. That is exactly what I'm looking for. The ability to show the css of all classnames used in the component so that a designer can reference them easily in the panel aside the component. This would help greatly, thank you again.
